ruby maze.rb > test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
ruby maze.rb >> test.txt
mv test.txt input_iclab086.txt
